### ISSUE TITLE
Usage hints for multiple await statements.

### ISSUE THREAD

**Issue by mesqueeb** [Kelin2025/async-nocatch#1]
Currently
`const { success, result } = await nocatchFetch('https://api.github.com/users')`
will result in `success` and `result` being only usable once.

I have about 5 await statements and would best like to add a single catch event at the bottom. Any ideas how to do this?

**Comment by Kelin2025** [comment]
```js
const results = await Promise.all([
  nocatchFetch(...),
  nocatchFetch(...),
  nocatchFetch(...)
])

if (results.some(res => !res.success)) {
  // Something is wrong
} else {
  // Everything is fine 
}
```

**Comment by mesqueeb** [comment]
@Kelin2025 thanks you are amazing!
